"""
One-time step: add a functional "group" field to each entry in
data/snapshot/abilities_info.json, classifying every ability by what it does.

This is NOT run by the app. Run it manually once:

    python classify_abilities.py

The GROUPS map below was produced by individually reviewing each ability's
description against a functional taxonomy (the user's base groups plus a few
additional groups: Item Interaction, Priority Modifiers, Low HP / Pinch,
Self Type Change, On Switch Out, Ignores Opponent). Abilities with no honest
fit are left without a group (no "group" key is written for them).

Editing a classification: change the value here and re-run — the script
rewrites the "group" field on every entry from this map (idempotent).
"""
import json
from pathlib import Path

BASE = Path(__file__).parent
ABILITIES_FILE = BASE / "data/snapshot/abilities_info.json"

GROUPS = {
    'ABILITY_SEED_SOWER': 'Terrains',
    'ABILITY_DAMP': 'Immunity to Moves',
    'ABILITY_ADAPTABILITY': 'Plain Stat or Move Buffs',
    'ABILITY_AERILATE': 'Move Type Changer',
    'ABILITY_AFTERMATH': 'On Being Knocked Out',
    'ABILITY_AIR_LOCK': 'Weather - Generic',
    'ABILITY_ANALYTIC': 'Plain Stat or Move Buffs',
    'ABILITY_ANGER_POINT': 'Status Reaction',
    'ABILITY_ANGER_SHELL': 'Low HP / Pinch',
    'ABILITY_ARMOR_TAIL': 'Priority Modifiers',
    'ABILITY_AROMA_VEIL': 'Double Battles',
    'ABILITY_BATTERY': 'Double Battles',
    'ABILITY_BATTLE_ARMOR': 'Protection from Status or Stat Changes',
    'ABILITY_BEAST_BOOST': 'On Knocking Out',
    'ABILITY_BERSERK': 'Low HP / Pinch',
    'ABILITY_BIG_PECKS': 'Protection from Status or Stat Changes',
    'ABILITY_BLAZE': 'Low HP / Pinch',
    'ABILITY_BULLETPROOF': 'Immunity to Moves',
    'ABILITY_CHEEK_POUCH': 'Item Interaction',
    'ABILITY_CHILLING_NEIGH': 'On Knocking Out',
    'ABILITY_CHLOROPHYLL': 'Weather - Sun',
    'ABILITY_CLEAR_BODY': 'Protection from Status or Stat Changes',
    'ABILITY_CLOUD_NINE': 'Weather - Generic',
    'ABILITY_COLOR_CHANGE': 'Self Type Change',
    'ABILITY_COMATOSE': 'Immunity to Status',
    'ABILITY_COMPETITIVE': 'Status Reaction',
    'ABILITY_COMPOUND_EYES': 'Plain Stat or Move Buffs',
    'ABILITY_COSTAR': 'Double Battles',
    'ABILITY_CUD_CHEW': 'Item Interaction',
    'ABILITY_CURIOUS_MEDICINE': 'Double Battles',
    'ABILITY_CURSED_BODY': 'On Receiving Contact',
    'ABILITY_CUTE_CHARM': 'On Receiving Contact',
    'ABILITY_DAUNTLESS_SHIELD': 'On Entering Battle',
    'ABILITY_DAZZLING': 'Priority Modifiers',
    'ABILITY_DEFEATIST': 'Low HP / Pinch',
    'ABILITY_DEFIANT': 'Status Reaction',
    'ABILITY_DOWNLOAD': 'On Entering Battle',
    'ABILITY_DRAGONIZE': 'Move Type Changer',
    'ABILITY_DRAGONS_MAW': 'Plain Type Buffs',
    'ABILITY_DRIZZLE': 'Weather - Rain',
    'ABILITY_DROUGHT': 'Weather - Sun',
    'ABILITY_DRY_SKIN': 'Weather - Sun',
    'ABILITY_EARTH_EATER': 'Immunity to Types',
    'ABILITY_EFFECT_SPORE': 'On Receiving Contact',
    'ABILITY_ELECTRIC_SURGE': 'Terrains',
    'ABILITY_EMERGENCY_EXIT': 'Low HP / Pinch',
    'ABILITY_FILTER': 'Resistance to Moves or Types',
    'ABILITY_FIRE_MANE': 'Plain Type Buffs',
    'ABILITY_FLAME_BODY': 'On Receiving Contact',
    'ABILITY_FLARE_BOOST': 'Buffs when with status',
    'ABILITY_FLASH_FIRE': 'Immunity to Types',
    'ABILITY_FLOWER_GIFT': 'Double Battles',
    'ABILITY_FLOWER_VEIL': 'Double Battles',
    'ABILITY_FLUFFY': 'Resistance to Moves or Types',
    'ABILITY_FRIEND_GUARD': 'Double Battles',
    'ABILITY_FRISK': 'On Entering Battle',
    'ABILITY_FULL_METAL_BODY': 'Protection from Status or Stat Changes',
    'ABILITY_FUR_COAT': 'Resistance to Moves or Types',
    'ABILITY_GALE_WINGS': 'Plain Type Buffs',
    'ABILITY_GALVANIZE': 'Move Type Changer',
    'ABILITY_GLUTTONY': 'Item Interaction',
    'ABILITY_GOOD_AS_GOLD': 'Immunity to Status',
    'ABILITY_GOOEY': 'On Receiving Contact',
    'ABILITY_GORILLA_TACTICS': 'Plain Stat or Move Buffs',
    'ABILITY_GRASSY_SURGE': 'Terrains',
    'ABILITY_GRASS_PELT': 'Terrains',
    'ABILITY_GRIM_NEIGH': 'On Knocking Out',
    'ABILITY_GUARD_DOG': 'Status Reaction',
    'ABILITY_GUTS': 'Buffs when with status',
    'ABILITY_HADRON_ENGINE': 'Terrains',
    'ABILITY_HARVEST': 'Item Interaction',
    'ABILITY_HEALER': 'Double Battles',
    'ABILITY_HEATPROOF': 'Resistance to Moves or Types',
    'ABILITY_HEAVY_METAL': 'Weight',
    'ABILITY_HOSPITALITY': 'Double Battles',
    'ABILITY_HUGE_POWER': 'Plain Stat or Move Buffs',
    'ABILITY_HUSTLE': 'Plain Stat or Move Buffs',
    'ABILITY_HYDRATION': 'Weather - Rain',
    'ABILITY_HYPER_CUTTER': 'Protection from Status or Stat Changes',
    'ABILITY_ICE_BODY': 'Weather - Hail',
    'ABILITY_ICE_SCALES': 'Resistance to Moves or Types',
    'ABILITY_IMMUNITY': 'Immunity to Status',
    'ABILITY_IMPOSTER': 'On Entering Battle',
    'ABILITY_INFILTRATOR': 'Immunity to Moves',
    'ABILITY_INNARDS_OUT': 'On Being Knocked Out',
    'ABILITY_INNER_FOCUS': 'Protection from Status or Stat Changes',
    'ABILITY_INSOMNIA': 'Immunity to Status',
    'ABILITY_INTIMIDATE': 'On Entering Battle',
    'ABILITY_INTREPID_SWORD': 'On Entering Battle',
    'ABILITY_IRON_BARBS': 'On Receiving Contact',
    'ABILITY_IRON_FIST': 'Plain Stat or Move Buffs',
    'ABILITY_JUSTIFIED': 'Status Reaction',
    'ABILITY_KEEN_EYE': 'Protection from Status or Stat Changes',
    'ABILITY_KLUTZ': 'Item Interaction',
    'ABILITY_LEAF_GUARD': 'Weather - Sun',
    'ABILITY_LEVITATE': 'Immunity to Types',
    'ABILITY_LIBERO': 'Move Type Changer',
    'ABILITY_LIGHTNING_ROD': 'Immunity to Types',
    'ABILITY_LIGHT_METAL': 'Weight',
    'ABILITY_LIMBER': 'Immunity to Status',
    'ABILITY_LINGERING_AROMA': 'Ability Change',
    'ABILITY_LIQUID_VOICE': 'Move Type Changer',
    'ABILITY_MAGICIAN': 'Item Interaction',
    'ABILITY_MAGMA_ARMOR': 'Immunity to Status',
    'ABILITY_MARVEL_SCALE': 'Buffs when with status',
    'ABILITY_MEGA_LAUNCHER': 'Plain Stat or Move Buffs',
    'ABILITY_MEGA_SOL': 'Weather - Sun',
    'ABILITY_MERCILESS': 'Plain Stat or Move Buffs',
    'ABILITY_MIMICRY': 'Terrains',
    'ABILITY_MINUS': 'Double Battles',
    'ABILITY_MIRROR_ARMOR': 'Status Reaction',
    'ABILITY_MISTY_SURGE': 'Terrains',
    'ABILITY_MOLD_BREAKER': 'Ignores Opponent',
    'ABILITY_MOTOR_DRIVE': 'Immunity to Types',
    'ABILITY_MOXIE': 'On Knocking Out',
    'ABILITY_MUMMY': 'Ability Change',
    'ABILITY_MYCELIUM_MIGHT': 'Priority Modifiers',
    'ABILITY_NATURAL_CURE': 'On Switch Out',
    'ABILITY_NEUROFORCE': 'Plain Stat or Move Buffs',
    'ABILITY_NEUTRALIZING_GAS': 'Ability Change',
    'ABILITY_NORMALIZE': 'Self Type Change',
    'ABILITY_NO_GUARD': 'Ignores Opponent',
    'ABILITY_OBLIVIOUS': 'Immunity to Status',
    'ABILITY_OPPORTUNIST': 'Status Reaction',
    'ABILITY_ORICHALCUM_PULSE': 'Weather - Sun',
    'ABILITY_OVERCOAT': 'Weather - Generic',
    'ABILITY_OVERGROW': 'Low HP / Pinch',
    'ABILITY_OWN_TEMPO': 'Immunity to Status',
    'ABILITY_PARENTAL_BOND': 'Plain Stat or Move Buffs',
    'ABILITY_PASTEL_VEIL': 'Immunity to Status',
    'ABILITY_PERISH_BODY': 'On Receiving Contact',
    'ABILITY_PICKPOCKET': 'On Receiving Contact',
    'ABILITY_PICKUP': 'Item Interaction',
    'ABILITY_PIXILATE': 'Move Type Changer',
    'ABILITY_PLUS': 'Double Battles',
    'ABILITY_POISON_HEAL': 'Buffs when with status',
    'ABILITY_POISON_POINT': 'On Receiving Contact',
    'ABILITY_POISON_TOUCH': 'On Making Contact',
    'ABILITY_POWER_OF_ALCHEMY': 'Double Battles',
    'ABILITY_POWER_SPOT': 'Double Battles',
    'ABILITY_PRANKSTER': 'Priority Modifiers',
    'ABILITY_PRISM_ARMOR': 'Resistance to Moves or Types',
    'ABILITY_PROTEAN': 'Self Type Change',
    'ABILITY_PROTOSYNTHESIS': 'Weather - Sun',
    'ABILITY_PSYCHIC_SURGE': 'Terrains',
    'ABILITY_PUNK_ROCK': 'Plain Stat or Move Buffs',
    'ABILITY_PURE_POWER': 'Plain Stat or Move Buffs',
    'ABILITY_PURIFYING_SALT': 'Immunity to Status',
    'ABILITY_QUARK_DRIVE': 'Terrains',
    'ABILITY_QUEENLY_MAJESTY': 'Priority Modifiers',
    'ABILITY_QUICK_DRAW': 'Priority Modifiers',
    'ABILITY_QUICK_FEET': 'Buffs when with status',
    'ABILITY_RAIN_DISH': 'Weather - Rain',
    'ABILITY_RATTLED': 'Status Reaction',
    'ABILITY_RECEIVER': 'Double Battles',
    'ABILITY_RECKLESS': 'Plain Stat or Move Buffs',
    'ABILITY_REFRIGERATE': 'Move Type Changer',
    'ABILITY_REGENERATOR': 'On Switch Out',
    'ABILITY_RIPEN': 'Item Interaction',
    'ABILITY_ROCKY_PAYLOAD': 'Plain Type Buffs',
    'ABILITY_ROUGH_SKIN': 'On Receiving Contact',
    'ABILITY_SAND_FORCE': 'Weather - Sandstorm',
    'ABILITY_SAND_RUSH': 'Weather - Sandstorm',
    'ABILITY_SAND_SPIT': 'Weather - Sandstorm',
    'ABILITY_SAND_STREAM': 'Weather - Sandstorm',
    'ABILITY_SAND_VEIL': 'Weather - Sandstorm',
    'ABILITY_SAP_SIPPER': 'Immunity to Types',
    'ABILITY_SCRAPPY': 'Ignores Opponent',
    'ABILITY_SCREEN_CLEANER': 'On Switch Out',
    'ABILITY_SHADOW_SHIELD': 'Resistance to Moves or Types',
    'ABILITY_SHARPNESS': 'Plain Stat or Move Buffs',
    'ABILITY_SHED_SKIN': 'Immunity to Status',
    'ABILITY_SHELL_ARMOR': 'Resistance to Moves or Types',
    'ABILITY_SHIELD_DUST': 'Protection from Status or Stat Changes',
    'ABILITY_SLUSH_RUSH': 'Weather - Hail',
    'ABILITY_SNOW_CLOAK': 'Weather - Hail',
    'ABILITY_SNOW_WARNING': 'Weather - Hail',
    'ABILITY_SOLAR_POWER': 'Weather - Sun',
    'ABILITY_SOLID_ROCK': 'Resistance to Moves or Types',
    'ABILITY_SOUNDPROOF': 'Immunity to Moves',
    'ABILITY_SPEED_BOOST': 'Plain Stat or Move Buffs',
    'ABILITY_SPICY_SPRAY': 'On Receiving Contact',
    'ABILITY_STAKEOUT': 'Plain Stat or Move Buffs',
    'ABILITY_STALL': 'Priority Modifiers',
    'ABILITY_STALWART': 'Ignores Opponent',
    'ABILITY_STAMINA': 'Status Reaction',
    'ABILITY_STATIC': 'On Receiving Contact',
    'ABILITY_STEADFAST': 'Status Reaction',
    'ABILITY_STEAM_ENGINE': 'Status Reaction',
    'ABILITY_STEELWORKER': 'Plain Type Buffs',
    'ABILITY_STEELY_SPIRIT': 'Plain Type Buffs',
    'ABILITY_STENCH': 'Plain Stat or Move Buffs',
    'ABILITY_STICKY_HOLD': 'Item Interaction',
    'ABILITY_STORM_DRAIN': 'Immunity to Types',
    'ABILITY_STRONG_JAW': 'Plain Stat or Move Buffs',
    'ABILITY_SUPERSWEET_SYRUP': 'On Entering Battle',
    'ABILITY_SUPER_LUCK': 'Plain Stat or Move Buffs',
    'ABILITY_SURGE_SURFER': 'Terrains',
    'ABILITY_SWARM': 'Plain Type Buffs',
    'ABILITY_SWEET_VEIL': 'Double Battles',
    'ABILITY_SWIFT_SWIM': 'Weather - Rain',
    'ABILITY_SYMBIOSIS': 'Double Battles',
    'ABILITY_SYNCHRONIZE': 'Status Reaction',
    'ABILITY_TANGLING_HAIR': 'On Receiving Contact',
    'ABILITY_TECHNICIAN': 'Plain Stat or Move Buffs',
    'ABILITY_TELEPATHY': 'Double Battles',
    'ABILITY_TERA_SHELL': 'Resistance to Moves or Types',
    'ABILITY_TERA_SHIFT': 'On Entering Battle',
    'ABILITY_THERMAL_EXCHANGE': 'Status Reaction',
    'ABILITY_THICK_FAT': 'Resistance to Moves or Types',
    'ABILITY_TINTED_LENS': 'Plain Stat or Move Buffs',
    'ABILITY_TORRENT': 'Low HP / Pinch',
    'ABILITY_TOUGH_CLAWS': 'Plain Stat or Move Buffs',
    'ABILITY_TOXIC_BOOST': 'Buffs when with status',
    'ABILITY_TOXIC_CHAIN': 'On Making Contact',
    'ABILITY_TOXIC_DEBRIS': 'Status Reaction',
    'ABILITY_TRACE': 'On Entering Battle',
    'ABILITY_TRANSISTOR': 'Plain Type Buffs',
    'ABILITY_TRIAGE': 'Priority Modifiers',
    'ABILITY_UNAWARE': 'Ignores Opponent',
    'ABILITY_UNBURDEN': 'Item Interaction',
    'ABILITY_UNNERVE': 'On Entering Battle',
    'ABILITY_VICTORY_STAR': 'Double Battles',
    'ABILITY_VITAL_SPIRIT': 'Immunity to Status',
    'ABILITY_VOLT_ABSORB': 'Immunity to Types',
    'ABILITY_WANDERING_SPIRIT': 'Ability Change',
    'ABILITY_WATER_ABSORB': 'Immunity to Types',
    'ABILITY_WATER_BUBBLE': 'Resistance to Moves or Types',
    'ABILITY_WATER_COMPACTION': 'Status Reaction',
    'ABILITY_WATER_VEIL': 'Immunity to Status',
    'ABILITY_WEAK_ARMOR': 'Status Reaction',
    'ABILITY_WELL_BAKED_BODY': 'Immunity to Types',
    'ABILITY_WHITE_SMOKE': 'Protection from Status or Stat Changes',
    'ABILITY_WIMP_OUT': 'Low HP / Pinch',
    'ABILITY_WIND_POWER': 'Status Reaction',
    'ABILITY_WIND_RIDER': 'Immunity to Types',
    'ABILITY_WONDER_GUARD': 'Immunity to Types',
}


def main():
    if not ABILITIES_FILE.exists():
        print(f"ERROR: {ABILITIES_FILE} not found. Run `python parse_abilities.py` first.")
        return 1

    data = json.loads(ABILITIES_FILE.read_text())

    unknown = [aid for aid in GROUPS if aid not in data]
    if unknown:
        print(f"WARNING: {len(unknown)} group IDs not present in snapshot: {unknown}")

    grouped = 0
    for aid, info in data.items():
        group = GROUPS.get(aid)
        if group:
            info["group"] = group
            grouped += 1
        else:
            info.pop("group", None)  # keep ungrouped entries clean on re-run

    ABILITIES_FILE.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"Wrote groups: {grouped} grouped / {len(data)} total "
          f"({len(data) - grouped} ungrouped).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
